apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      hostNetwork: true
      containers:
        - name: server
          image: localhost:5000/server_docker:latest
          ports:
            - containerPort: 9000
